name: C++ Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake clang

    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Lint with clang-format
      run: |
        # Check for formatting issues using clang-format
        if [ -n "$(clang-format -style=file -output-replacements-xml $(find . -name '*.cpp' -o -name '*.h'))" ]; then
          echo "Code formatting issues found. Please run clang-format to fix them."
          exit 1
        fi

    - name: Test with CTest
      run: |
        cd build
        ctest

