name: C++ Linter and Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build and Run C++ Program
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Clang tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang

      - name: Run Clang-Tidy (Linting)
        run: |
          clang-tidy main.cpp -- -std=c++11

      - name: Compile C++ Program
        run: |
          clang++ -o my_program main.cpp

      - name: Run C++ Program
        run: ./my_program
