name: DiceLinter

on: [push]

jobs:
  build:
    name: DiceLinter
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compile C++ Code
        run: clang++ *.cpp -o DiceRoller

      - name: Run Tests
        run: ./DiceRoller -test
