name: DiceRoller

on: [push]

jobs:
  build:
    name: DiceRoller
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compile C++ Code
        run: g++ *.cpp -o DiceRoller

      - name: Run Tests
        run: |
          # Execute the program with predefined input
          ./DiceRoller <<EOF
          1  # Input choice 1 (simulate rolling the dice)
          3  # Input choice 3 (simulate checking stats)
          -1 # Input choice -1 (simulate quitting)
          EOF
