name: DiceRoller

on:
  push:
    branches:
      - main

jobs:
  build:
    name: DiceRoller
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy

      - name: Compile C++ Code
        run: g++ *.cpp -o DiceRoller

      - name: Test Program
        run: |
          ./DiceRoller

      - name: Run Linter
        run: |
          clang-tidy *.cpp -checks=bugprone-*,modernize-*,performance-* -- -std=c++11
