name: Lint Code Base

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Clang-Format
        run: sudo apt-get install clang-format

      - name: Format C++ Files
        run: |
          clang-format --version
          find . -name "*.cpp" -o -name "*.h" -exec clang-format -i --style=file {} +

      - name: Exclude GitHub Actions Workflows
        run: |
          find . -path './.github/workflows/*.yml' -exec rm -f {} +

      - name: Lint Code
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
