name: Lint Code Base

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    name: Lint C++ Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Clang tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang

      - name: Run Clang-Tidy
        run: |
          # Run clang-tidy on all .cpp and .h files in the repository
          find . -name "*.cpp" -o -name "*.h" | xargs clang-tidy

      - name: Display Results
        run: |
          echo "Clang-Tidy Analysis Completed"
