name: Check Python application

on: [push]

env:
  MIN_COVERAGE_REQUIRED: 75

jobs:
  python-test-check:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover
        echo "Coverage data files:"
        ls -l .coverage*

    - name: Generate coverage report
      run: coverage report -m
