name: Check Python application

on: [push]

env:
  MIN_COVERAGE_REQUIRED: 75

jobs:
  python-test-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage  # Install coverage package

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover
        echo "Coverage data files:"
        ls -l .coverage*  # List coverage data files for debugging

    - name: Calculate coverage percentage
      id: total-coverage
      run: |
        if [ -f .coverage ]; then
          coverage report -m  # Generate coverage report
          coverage json -q -o coverage.json || echo "Failed to generate JSON report"
          coverage_percentage=$(coverage report | awk 'NR==2{print substr($4, 1, length($4)-1)}')
          is_covered=$(awk 'BEGIN{print "'"$coverage_percentage"'" >= ENVIRON["MIN_COVERAGE_REQUIRED"] ? "true" : "false"}')
          echo "Coverage is: $coverage_percentage"
          echo "::set-output name=is_covered::$is_covered"
        else
          echo "No coverage data collected."
          exit 1
        fi
